"""add artist about column

Revision ID: 0572d1a39022
Revises: 0ab1b827499b
Create Date: 2023-12-21 12:46:07.959845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0572d1a39022'
down_revision: Union[str, None] = '0ab1b827499b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'about')
    # ### end Alembic commands ###
