"""Billboard unique constraints

Revision ID: 0650feea2b8d
Revises: 24a53a46ddea
Create Date: 2023-11-27 19:27:55.782646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0650feea2b8d'
down_revision: Union[str, None] = '24a53a46ddea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'billboard_chart_entries', ['billboard_id', 'chart', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billboard_chart_entries', type_='unique')
    # ### end Alembic commands ###
