"""Add genius artist id column

Revision ID: 06bb4679e295
Revises: d83acd20b1c3
Create Date: 2024-07-02 09:42:05.039065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bb4679e295'
down_revision: Union[str, None] = 'd83acd20b1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genius_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genius_id')
    # ### end Alembic commands ###
