"""Make has_about_document not nullable

Revision ID: 0dd9e0d9596f
Revises: d4493e394b93
Create Date: 2024-07-18 21:19:02.428041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd9e0d9596f'
down_revision: Union[str, None] = 'd4493e394b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_artists', 'has_about_document',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_artists', 'has_about_document',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
