"""embeddings non-null constraint

Revision ID: 0f8daceba5e6
Revises: 88875ef86735
Create Date: 2023-12-08 09:33:00.309741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8daceba5e6'
down_revision: Union[str, None] = '88875ef86735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_tracks', 'has_name_embeddings',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_tracks', 'has_name_embeddings',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
