"""add_playlist_id_column

Revision ID: 132a498067f4
Revises: fcf185764441
Create Date: 2024-03-01 19:53:20.418422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132a498067f4'
down_revision: Union[str, None] = 'fcf185764441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('playlist_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'playlist_id')
    # ### end Alembic commands ###
