"""Remove legacy billboard tables

Revision ID: 14066991e400
Revises: ff98f5d6a95a
Create Date: 2025-09-26 10:31:34.370306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14066991e400'
down_revision: Union[str, None] = 'ff98f5d6a95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billboard_chart_entries')
    op.drop_table('billboard_tracks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billboard_tracks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weeks_on_chart', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='billboard_tracks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('billboard_chart_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('billboard_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chart', postgresql.ENUM('HOT_100', name='billboardchart'), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('position', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('peak_position', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('last_position', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboard_tracks.id'], name='billboard_chart_entries_billboard_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billboard_chart_entries_pkey'),
    sa.UniqueConstraint('billboard_id', 'chart', 'date', name='billboard_chart_entries_billboard_id_chart_date_key')
    )
    # ### end Alembic commands ###
