"""Billboard orms

Revision ID: 198984bd0e84
Revises: 1eb199cddfb9
Create Date: 2023-11-10 12:16:26.968680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198984bd0e84'
down_revision: Union[str, None] = '1eb199cddfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billboard_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('weeks_on_chart', sa.SmallInteger(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billboard_chart_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billboard_id', sa.String(), nullable=False),
    sa.Column('chart', sa.Enum('HOT_100', name='billboardchart'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('peak_position', sa.SmallInteger(), nullable=True),
    sa.Column('last_position', sa.SmallInteger(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboard_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billboard_chart_entries')
    op.drop_table('billboard_tracks')
    # ### end Alembic commands ###
