"""Initial

Revision ID: 1eb199cddfb9
Revises: 
Create Date: 2023-11-10 10:49:37.579191

"""
import asyncio
from functools import partial
from typing import Sequence, Union

import nest_asyncio

from genie_datastores.postgres.models import (
    SpotifyArtist,
    SpotifyTrack,
    SpotifyAlbum,
    AudioFeatures,
    TrackLyrics,
    TrackIDMapping,
    RadioTrack
)
from genie_datastores.postgres.models.orm.base_orm_model import Base
from genie_datastores.postgres.operations import get_database_engine

# revision identifiers, used by Alembic.
revision: str = '1eb199cddfb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


async def create_initial_tables() -> None:
    orms = [
        SpotifyAlbum,
        SpotifyArtist,
        SpotifyTrack,
        AudioFeatures,
        RadioTrack,
        TrackIDMapping,
        TrackLyrics
    ]
    tables = [orm.__table__ for orm in orms]
    engine = get_database_engine()

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(partial(Base.metadata.create_all, tables=tables))


def upgrade() -> None:
    loop = asyncio.get_event_loop()
    nest_asyncio.apply(loop)
    loop.run_until_complete(create_initial_tables())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
