"""Shazam orms

Revision ID: 24a53a46ddea
Revises: 2e483713d2a5
Create Date: 2023-11-23 21:39:19.592946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a53a46ddea'
down_revision: Union[str, None] = '198984bd0e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shazam_artists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('birth_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('similar_artists', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shazam_top_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('location', sa.Enum('TEL_AVIV', 'HAIFA', 'NETANYA', 'JERUSALEM', 'BEER_SHEBA', 'ISRAEL', 'WORLD', name='shazamlocation'), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'location', 'position')
    )
    op.create_table('shazam_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('writers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('primary_genre', sa.String(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['shazam_artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shazam_tracks')
    op.drop_table('shazam_top_tracks')
    op.drop_table('shazam_artists')
    # ### end Alembic commands ###
