"""Add translations id serial columns

Revision ID: 28cd76c4a0b1
Revises: f586598d3368
Create Date: 2024-05-31 14:00:46.030506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, func
from sqlalchemy.sql.ddl import CreateSequence

# revision identifiers, used by Alembic.
revision: str = '28cd76c4a0b1'
down_revision: Union[str, None] = 'f586598d3368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.execute(
        text(
            """
            CREATE SEQUENCE translations_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
            """
        )
    )
    seq = sa.schema.Sequence('translations_id_seq')
    op.alter_column("translations", "id", server_default=func.next_value(seq))
    op.execute(
        text(
            """
            UPDATE translations
            SET id=nextval('translations_id_seq')
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'id')
    # ### end Alembic commands ###
