"""make chart key column nullable

Revision ID: 2a42b3f17e1a
Revises: e5e3c2044a6f
Create Date: 2024-01-18 15:34:07.766529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a42b3f17e1a'
down_revision: Union[str, None] = '8935d4b04386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charts_entries', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charts_entries', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
