"""Has name embeddings

Revision ID: 3b78b55159b1
Revises: 8c68058d20da
Create Date: 2023-12-08 09:25:07.530286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b78b55159b1'
down_revision: Union[str, None] = '0650feea2b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_tracks', sa.Column('has_name_embeddings', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_tracks', 'has_name_embeddings')
    # ### end Alembic commands ###
