"""add_batch_id_column

Revision ID: 3f407bc136c9
Revises: 3ed1eea36432
Create Date: 2024-05-10 11:39:58.312925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f407bc136c9'
down_revision: Union[str, None] = '3ed1eea36432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('batch_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'batch_id')
    # ### end Alembic commands ###
