"""remove_israeli_source_column

Revision ID: 5b23c3100284
Revises: 9316e1f16bcc
Create Date: 2024-02-08 19:05:01.169336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from genie_datastores.postgres.models import DataSource

# revision identifiers, used by Alembic.
revision: str = '5b23c3100284'
down_revision: Union[str, None] = '9316e1f16bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'is_israeli_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('is_israeli_source', postgresql.ENUM('MANUAL_TAGGING', 'OPENAI', 'ISRAELI_WIKIPEDIA', 'GENERAL_WIKIPEDIA', 'SPOTIFY_EQUAL_PLAYLISTS', 'GOOGLE_IMAGES', 'SHAZAM', 'MUSIXMATCH', 'GENIUS', 'SPOTIFY_IMAGES', name='datasource'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
