"""Add genius artists table

Revision ID: 6c51f240146d
Revises: 06bb4679e295
Create Date: 2024-07-03 09:48:50.728066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c51f240146d'
down_revision: Union[str, None] = '06bb4679e295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genius_artists',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alternate_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('facebook_name', sa.String(), nullable=True),
    sa.Column('instagram_name', sa.String(), nullable=True),
    sa.Column('twitter_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genius_artists')
    # ### end Alembic commands ###
