"""add_evidence_and_origin_columns

Revision ID: 7ac1e91e1f3a
Revises: 88c5d940ef41
Create Date: 2024-02-24 15:35:02.742808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from genie_datastores.postgres.models import DataSource

# revision identifiers, used by Alembic.
revision: str = '7ac1e91e1f3a'
down_revision: Union[str, None] = '88c5d940ef41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('origin', sa.String(), nullable=True))
    op.drop_column('artists', 'primary_genre')
    op.add_column('decisions', sa.Column('evidence', sa.String(), nullable=True))
    op.execute(sa.text(f"ALTER TYPE datasource ADD value '{DataSource.SPOTIFY.name}'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'evidence')
    op.add_column('artists', sa.Column('primary_genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'origin')
    # ### end Alembic commands ###
