"""translations id primary key

Revision ID: 82a5e756e3be
Revises: 28cd76c4a0b1
Create Date: 2024-05-31 14:33:13.972360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a5e756e3be'
down_revision: Union[str, None] = '28cd76c4a0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('translations_id_seq'::regclass)"))
    op.drop_constraint("translations_pkey", "translations", "primary")
    op.create_primary_key("translations_pkey", "translations", ["id", ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text("nextval('translations_id_seq'::regclass)"))
    op.drop_constraint("translations_pkey", "translations", "primary")
    op.create_primary_key("translations_pkey", "translations", ["entity_id", ])
    # ### end Alembic commands ###
