"""Fill embeddings null values

Revision ID: 88875ef86735
Revises: 3b78b55159b1
Create Date: 2023-12-08 09:30:00.296988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '88875ef86735'
down_revision: Union[str, None] = '3b78b55159b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "UPDATE spotify_tracks SET has_name_embeddings=false"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
