"""add_genres_table

Revision ID: 88c5d940ef41
Revises: f29de397d90b
Create Date: 2024-02-13 18:57:15.601565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '88c5d940ef41'
down_revision: Union[str, None] = 'f29de397d90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('primary_genre', ENUM('ELECTRONIC', 'HIP_HOP', 'INDIE', 'JAZZ', 'MIZRAHI', 'OTHER', 'POP', 'ROCK', 'SINGER_SONGWRITER', 'SOUL', name='primarygenre', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        sa.text(
            "ALTER TABLE genres ADD constraint check_id_lowercase CHECK (id ~ '^[a-z]+$')"
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    # ### end Alembic commands ###
