"""add charts table

Revision ID: 8935d4b04386
Revises: 0a5baddd852f
Create Date: 2024-01-06 09:32:06.634630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8935d4b04386'
down_revision: Union[str, None] = '0a5baddd852f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts_entries',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('chart', sa.Enum('BILLBOARD_HOT_100', 'GALATZ_WEEKLY_ISRAELI', 'GLGLZ_WEEKLY_INTERNATIONAL', 'GLGLZ_WEEKLY_ISRAELI', 'KOL_ISRAEL_WEEKLY_INTERNATIONAL', 'KOL_ISRAEL_WEEKLY_ISRAELI', name='chart'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['spotify_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'chart', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charts_entries')
    # ### end Alembic commands ###
