"""remove_old_embeddings_column_and_disallow_nulls

Revision ID: 9316e1f16bcc
Revises: b0b875ec886b
Create Date: 2024-02-03 15:33:51.484327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9316e1f16bcc'
down_revision: Union[str, None] = 'b0b875ec886b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_tracks', 'has_name_embeddings')
    op.alter_column('tracks', 'has_name_embeddings',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tracks', 'is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tracks', 'has_name_embeddings',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('spotify_tracks', sa.Column('has_name_embeddings', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
