"""Add shazam_artists about column

Revision ID: 9d4df5af2a02
Revises: de9025052674
Create Date: 2024-07-25 18:48:43.730950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4df5af2a02'
down_revision: Union[str, None] = 'de9025052674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shazam_artists', sa.Column('has_about_document', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shazam_artists', 'has_about_document')
    # ### end Alembic commands ###
