"""copy_embeddings_column_to_tracks_table

Revision ID: b0b875ec886b
Revises: f612e4ab4456
Create Date: 2024-02-03 15:23:01.408590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b875ec886b'
down_revision: Union[str, None] = 'f612e4ab4456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('has_name_embeddings', sa.Boolean(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE tracks SET has_name_embeddings = spotify_tracks.has_name_embeddings FROM spotify_tracks "
            "WHERE tracks.id = spotify_tracks.id"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'has_name_embeddings')
    # ### end Alembic commands ###
