"""add_endpoint_column_to_cases

Revision ID: b70ab2ff18f8
Revises: e026c1f748d8
Create Date: 2024-02-29 19:07:23.938079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'b70ab2ff18f8'
down_revision: Union[str, None] = 'e026c1f748d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE TYPE playlistendpoint AS ENUM ('CONFIGURATION', 'EXISTING_PLAYLIST', 'FOR_YOU', 'PHOTO', 'PROMPT', 'WRAPPED')"))
    op.add_column('cases', sa.Column('endpoint', ENUM('CONFIGURATION', 'EXISTING_PLAYLIST', 'FOR_YOU', 'PHOTO', 'PROMPT', 'WRAPPED', name='playlistendpoint', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'endpoint')
    # ### end Alembic commands ###
