"""tracks_and_decisions_tables

Revision ID: bc99287abfc5
Revises: 2183515c6cc5
Create Date: 2024-01-27 17:37:58.945485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'bc99287abfc5'
down_revision: Union[str, None] = '2183515c6cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column', sa.String(), nullable=False),
    sa.Column('source', ENUM('GENERAL_WIKIPEDIA', 'GENIUS', 'GOOGLE_IMAGES', 'ISRAELI_WIKIPEDIA', 'MANUAL_TAGGING', 'MUSIXMATCH', 'OPENAI', 'SHAZAM', 'SPOTIFY_EQUAL_PLAYLISTS', 'SPOTIFY_IMAGES', name='datasource', create_type=False), nullable=False),
    sa.Column('table', ENUM('ARTISTS', 'TRACKS', 'TRACKS_LYRICS', name='table', create_type=False), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('primary_genre', ENUM('ELECTRONIC', 'HIP_HOP', 'INDIE', 'JAZZ', 'MIZRAHI', 'OTHER', 'POP', 'ROCK', 'SINGER_SONGWRITER', 'SOUL', name='primarygenre', create_type=False), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['spotify_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('decisions')
    # ### end Alembic commands ###
