"""add_has_exception_column_to_cases_progress

Revision ID: c3fcc5e36ed7
Revises: b70ab2ff18f8
Create Date: 2024-02-29 19:49:39.498357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fcc5e36ed7'
down_revision: Union[str, None] = 'b70ab2ff18f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases_progress', sa.Column('has_exception', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases_progress', 'has_exception')
    # ### end Alembic commands ###
