"""Add has_about_document column

Revision ID: c900145b1ea5
Revises: 6c51f240146d
Create Date: 2024-07-18 21:08:52.641891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c900145b1ea5'
down_revision: Union[str, None] = '6c51f240146d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('has_about_document', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'has_about_document')
    # ### end Alembic commands ###
