"""Remove spotify_artists about column

Revision ID: de9025052674
Revises: 0dd9e0d9596f
Create Date: 2024-07-23 09:16:02.602412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9025052674'
down_revision: Union[str, None] = '0dd9e0d9596f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'about')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
