"""audio features column to small integer

Revision ID: edce136d56b9
Revises: 1c4ab9f09748
Create Date: 2023-11-11 12:05:30.566116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edce136d56b9'
down_revision: Union[str, None] = '1c4ab9f09748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_features', 'acousticness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'danceability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'energy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'instrumentalness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'liveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'speechiness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('audio_features', 'valence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_features', 'valence',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'speechiness',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'liveness',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'instrumentalness',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'energy',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'danceability',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audio_features', 'acousticness',
               existing_type=sa.SmallInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
