"""Remove birth_date_source and gender_source columns

Revision ID: ee7603fdba60
Revises: 9f17275ec55b
Create Date: 2025-11-29 15:49:28.187166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee7603fdba60'
down_revision: Union[str, None] = '9f17275ec55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'birth_date_source')
    op.drop_column('artists', 'gender_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('gender_source', postgresql.ENUM('MANUAL_TAGGING', 'OPENAI', 'ISRAELI_WIKIPEDIA', 'GENERAL_WIKIPEDIA', 'SPOTIFY_EQUAL_PLAYLISTS', 'GOOGLE_IMAGES', 'SHAZAM', 'MUSIXMATCH', 'GENIUS', 'SPOTIFY_IMAGES', 'CHARTS', 'SPOTIFY', 'WIKIPEDIA', 'JOSIE', name='datasource'), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('birth_date_source', postgresql.ENUM('MANUAL_TAGGING', 'OPENAI', 'ISRAELI_WIKIPEDIA', 'GENERAL_WIKIPEDIA', 'SPOTIFY_EQUAL_PLAYLISTS', 'GOOGLE_IMAGES', 'SHAZAM', 'MUSIXMATCH', 'GENIUS', 'SPOTIFY_IMAGES', 'CHARTS', 'SPOTIFY', 'WIKIPEDIA', 'JOSIE', name='datasource'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
