"""Remove shazam_artists about column

Revision ID: f19a7ff69783
Revises: 0c58b4601324
Create Date: 2024-07-26 12:20:26.795704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19a7ff69783'
down_revision: Union[str, None] = '0c58b4601324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shazam_artists', 'about')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shazam_artists', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
