"""Add curation tables

Revision ID: fe9b19181cab
Revises: 14066991e400
Create Date: 2025-10-14 12:10:26.946154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'fe9b19181cab'
down_revision: Union[str, None] = '14066991e400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE datasource ADD VALUE 'JOSIE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curators',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', ENUM('GENERAL_WIKIPEDIA', 'GENIUS', 'GOOGLE_IMAGES', 'ISRAELI_WIKIPEDIA', 'JOSIE', 'MANUAL_TAGGING', 'MUSIXMATCH', 'OPENAI', 'SHAZAM', 'SPOTIFY_EQUAL_PLAYLISTS', 'SPOTIFY_IMAGES', 'CHARTS', 'SPOTIFY', 'WIKIPEDIA', name='datasource', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curator_collections',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('curator_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curated_tracks',
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection'], ['curator_collections.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['spotify_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'collection')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curated_tracks')
    op.drop_table('curator_collections')
    op.drop_table('curators')
    # ### end Alembic commands ###
